# Part 01. 파이썬 기초 핵심 과정
### ch 43~45. (10. 예외 - 01. 에러 및 예외 처리(1),(2),(3))

 - 완벽한 프로그램은 존재할 수 없고, 코드가 아무리 완벽해도 하드웨어에서 나타나는 에러를 처리하기 힘듦 

- 예외 처리를 통해 에러 발생시 내가 의도한 대로 코드를 실행하게 해놓고, 바로바로 수정해야 함

## 다양한 Exceptions
- 파이썬 예외 종류
- 문법적 에러 발생 실습
- 런타임 에러 발생 실습
- Try-except-else-finally

##  예외 처리 실습
```python
# Section10
# 파이썬 예외처리

# 예외 종류
# 문법적으로 에러가 없지만, 코드 실행(런타임) 프로세스에서 발생하는 예외 처리도 중요
# linter : 코드 스타일, 문법 체크

# SyntaxError : 잘못된 문법
# print('Test)->에러
# if True ->에러
#     pass
# x => y ->에러

# NameError : 참조변수 없음
# a=10
# b=15
# print(c) ->에러

# ZeroDivisionError : 0 나누기 에러
# print(10/0) ->에러

# IndexError : 인덱스 범위 오버
# x=[10,20,30]
# print(x[3]) ->에러

# KeyError
# dic={'name':'kim', 'age':33,'city':'seoul'}
# print(dic['hobby'])->에러
 # 딕셔너리에서 키에 접근할 때에는 print(dic.get('hobby'))로 접근하면 에러를 피할수있음

# AttributeError : 모듈, 클래스에 있는 잘못된 속성 사용시에 예외
# import time
# print(time.time())
# print(time.month()) -> 에러

# ValueError : 참조값이 없을 때 발생
# x=[1,5,9]
# x.remove(10) -> 에러
# x.index(10) -> 에러

# FileNotFoundError
# f=open('test.txt','r') # test란 파일이 없기 때문에 예외발생 -> 에러

# TypeError
x=[1,2]
y=(1,2)
z='test'
# print(x+y) -> 에러
# print(x+z) -> 에러
# 위와 같은 경우 형변환해야 함

# 항상 예외가 발생하지 않을 것으로 가정하고 먼저 코딩
# 그 후 런타임 예외 발생시 예외 처리 코딩 권장

# 예외 처리 기본
# try : 에러가 발생할 가능성이 있는 코드 실행
# except : 에러명 1
# except : 에러명 2
# else : 에러가 발생하지 않았을 경우 실행
# finally : 항상 실행

# 예제1
name = ['kim', 'lee', 'park']
# try: 
#     z = 'kim'
#     x = name.index(z)
#     print('{} Found it in name'.format(z, x+1))
# except ValueError: # 어떤 에러가 발생할지 모를때는 그냥 except만 써도 됨(모든 에러 캐치함)
#     print('Not Fount it!-Occured ValueError')
# else:
#     print('Ok!') # 에러가 발생하지 않았을 경우, 즉 try문이 정상적으로 실행되었을 때 출력

# 예제2
try: 
    z = 'kim'
    x = name.index(z)
    print('{} Found it in name'.format(z, x+1))
except ValueError:
    print('Not Fount it!-ValueError')
else:
    print('Ok!')
finally:
    print('finally ok')

# 예제3
# 예외 처리는 하지 않지만, 무조건 수행되는 코딩 패턴
try:
    print("Try")
finally:
    print('ok final')

# 예제4
try: 
    z = 'kim'
    x = name.index(z)
    print('{} Found it in name'.format(z, x+1))
except ValueError as v:
    print(v) # alias를 주고 그걸 프린트하면 에러내용이 자동 출력됨
except IndexError:
    print('Not Fount it!-IndexError')
except Exception:
    print('Not Fount it!-Error')
# except exception이 except 중 맨 위에 있다면, 오류를 잡고 바로 빠져나가기 때문에 valueerror인지 indexerror인지 모름. 따라서 순서를 잘 배치해야 함
else:
    print('Ok!')
finally:
    print('finally ok')

# 예제6
# 예제 발생 : raise
# raise 키워드로 예외 직접 발생
try:
    a='kim'
    if a=='kim':
        print('ok')
    else:
        raise ValueError
except ValueError:
    print('문제발생!')
except Exception as f:
    print(f)
else:
    

```

> Written with [StackEdit](https://stackedit.io/).
<!--stackedit_data:
eyJoaXN0b3J5IjpbLTUyOTIxNDYxNV19
-->